server:
  rootPath: /api/
database:
  driverClass: org.postgresql.Driver
  user: ${DB_USER:-dbu}
  password: ${DB_PASSWORD:-bidu}
  url: jdbc:postgresql://${DB_HOST:-localhost/calendarium}
  properties:
    charSet: UTF-8
thirdParty:
  env: ${ENV:-production}
  baseUrl: ${CALENDARIUM_BASE_URL:-https://calendarium.ca}
  accessKey: ${CODEBARDS_AWS_ACCESS_KEY:-bidu}
  secretKey: ${CODEBARDS_AWS_SECRET_KEY:-pouet}
  stripeApiKey: ${CODEBARDS_STRIPE_KEY:-yebo}
  stripeWebhookSecret: ${CODEBARDS_STRIPE_WEBHOOK_SECRET:-sodang}
