server:
  rootPath: /api/
database:
  driverClass: org.postgresql.Driver
  user: ${DB_USER:-dbu}
  password: ${DB_PASSWORD:-bidu}
  url: jdbc:postgresql://${DB_HOST:-localhost/calendarium}
  properties:
    charSet: UTF-8
thirdParty:
  env: ${ENV:-production}
  accessKey: ${POUTINE_AWS_ACCESS_KEY:-bidu}
  secretKey: ${POUTINE_AWS_SECRET_KEY:-pouet}
  stripeApiKey: ${CODEBARDS_STRIPE_KEY:-yebo}
