server:
  rootPath: /api/
database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:calendarium.db
  properties:
    charSet: UTF-8
    foreign_keys: true
thirdParty:
  env: ${ENV:-production}
  baseUrl: ${CALENDARIUM_BASE_URL:-https://calendarium.ca}
  accessKey: ${CODEBARDS_AWS_ACCESS_KEY:-bidu}
  secretKey: ${CODEBARDS_AWS_SECRET_KEY:-pouet}
  stripeApiKey: ${CODEBARDS_STRIPE_KEY:-yebo}
  stripeWebhookSecret: ${CODEBARDS_STRIPE_WEBHOOK_SECRET:-sodang}
